<!DOCTYPE html>
<html>
<head>
    <?php echo $this->headScript(); ?>    
	<title>SURFnet Tiqr Enrollment Portaal</title>
	<link rel="stylesheet" media="all" type="text/css" href="/css/style.css" />
</head>
<body>
<div class="wrapper">
	<div class="header">
    	<a href="/"><img class="logo" src="http://www.surfnet.nl/Style%20Library/SURFnet/img/surfnet_logo.gif" alt="surfnet logo" /></a>
    	<span>SURFnet Tiqr Enrollment Portaal</span>
	    <span class="left"></span>
	    <span class="right"></span>
    	<img src="http://www.surfnet.nl/Style%20Library/SURFnet/img/header_img.jpg" alt="header img" />
    	<ul>
    	</ul>
	</div>
	<div class="main">
		<div class="column content">
			<div class="item">
				<span class="h2">
					<span style="float: left">Enrollment</span>
				</span>
				<div class="pageContent">
					<?php echo $this->layout()->content; ?>		
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>